"use client"

import { useEffect, useMemo, useState } from "react"
import katex from "katex"
import { COLOR, Prompt, AltDemoCard, HelperRow, MixedText, type InteractionProps } from "./_shared"

export type AdjustSliderConfig = {
  prompt?: string
  /** Variable name shown in the readout, e.g. "k". */
  varName: string
  min: number
  max: number
  step: number
  initial: number
  /** Optional target value — if set, success fires when the student lands on it. */
  target?: number
  /** Tolerance for matching the target. */
  tolerance?: number
  /**
   * Function (as a string of JS body) that returns an SVG string for a given value.
   * Stored in JSON; eval'd via new Function. ONLY trusted lesson.json content.
   */
  renderSvg: string
  /** Optional success text. */
  successText?: string
  /** If true, advance the lesson on any movement (exploration mode, no target). */
  advanceOnExplore?: boolean
  /** Verify slides: no show-me reveal. Injected by InteractionSlide. */
  noHelp?: boolean
  /** Animated demonstration of the method, injected by LessonRunner when the
   *  student taps "explain another way". Shown ON the canvas, never in place
   *  of the question. */
  altDemo?: string
}

/**
 * AdjustSlider — slider drives a live visual. Two modes:
 *   1. with target: ManipulateAndVerify-lite, success when value matches.
 *   2. without target: pure exploration; the parent slide sets advance=manual.
 *
 * The visual is generated by a function in the config: it receives the current
 * value and returns an SVG string. Keeps the JSON declarative; the function
 * body is only ever as trusted as the lesson.json itself.
 */
export default function AdjustSlider({ config, onComplete, onDismissAlt, onShowMeUsed }: InteractionProps<AdjustSliderConfig>) {
  const tol = config.tolerance ?? config.step / 2
  const [value, setValue] = useState(config.initial)
  const [done, setDone] = useState(false)
  const [exploreFired, setExploreFired] = useState(false)

  // Compile the renderer during render (memoised). The previous version
  // compiled inside useEffect, which runs after the first paint, so the
  // visual was blank for one frame on every mount.
  const renderFn = useMemo<(v: number) => string>(() => {
    try {
      // eslint-disable-next-line @typescript-eslint/no-implied-eval, no-new-func
      return new Function("v", "color", `return (${config.renderSvg})(v, color)`) as (v: number) => string
    } catch (e) {
      return () => `<text x='10' y='20' fill='#ff4670'>renderSvg failed: ${(e as Error).message}</text>`
    }
  }, [config.renderSvg])

  // Success / explore-advance detection
  useEffect(() => {
    if (done) return
    if (config.target !== undefined && Math.abs(value - config.target) <= tol) {
      setDone(true)
      onComplete({ value })
      return
    }
    if (config.advanceOnExplore && !exploreFired && value !== config.initial) {
      setExploreFired(true)
      onComplete({ value, explore: true })
    }
  }, [value, config.target, tol, done, config.advanceOnExplore, config.initial, exploreFired, onComplete])

  // Live SVG
  const svgString = renderFn(value)

  // KaTeX for the readout
  const readoutTex = katex.renderToString(`${config.varName} = ${formatNum(value)}`, {
    throwOnError: false,
    displayMode: false,
    output: "html",
  })

  return (
    <div className="w-full flex flex-col items-center">
      <Prompt>{config.prompt}</Prompt>
      <AltDemoCard svg={config.altDemo} onDismiss={onDismissAlt} />

      <div
        className={`relative w-full max-w-[520px] rounded-xl border transition-colors duration-300 ${done ? "pl-success-pulse" : ""}`}
        style={{
          borderColor: done ? COLOR.green : COLOR.border,
          background: COLOR.card,
        }}
      >
        <div className="p-4 pb-2" dangerouslySetInnerHTML={{ __html: svgString }} />

        {/* Slider row */}
        <div className="px-5 pb-5 pt-3 border-t border-[#0f161f]">
          <div className="flex items-center justify-between mb-2.5">
            <span className="text-[11px] font-mono uppercase tracking-wider" style={{ color: COLOR.faint }}>
              drag to adjust
            </span>
            <span
              className="text-[15px] transition-colors duration-300"
              style={{ color: done ? COLOR.green : COLOR.white }}
              dangerouslySetInnerHTML={{ __html: readoutTex }}
            />
          </div>
          <input
            type="range"
            min={config.min}
            max={config.max}
            step={config.step}
            value={value}
            onChange={e => setValue(parseFloat(e.target.value))}
            className="w-full pl-range"
            style={{ accentColor: done ? COLOR.green : COLOR.blue }}
          />
          <div className="flex justify-between mt-1 text-[10px] font-mono" style={{ color: COLOR.faint }}>
            <span>{formatNum(config.min)}</span>
            <span>{formatNum(config.max)}</span>
          </div>
        </div>
      </div>

      {done && config.successText && (
        <MixedText
          text={config.successText}
          className="mt-5 block text-[16px] sm:text-[17px] text-[#0fee89] pl-reveal text-center max-w-[600px] leading-relaxed"
        />
      )}

      {!config.noHelp && (
        <HelperRow
          onShowMe={
            config.target !== undefined && !done
              ? () => { onShowMeUsed?.(); setValue(config.target!); setDone(true); onComplete({ value: config.target, revealed: true }) }
              : undefined
          }
        />
      )}
    </div>
  )
}

function formatNum(n: number): string {
  if (Number.isInteger(n)) return String(n)
  return n.toFixed(2).replace(/\.?0+$/, "")
}
